### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by lil5**
#89

### CODE REVIEW

**Comment by lil5** [comment]
there are so many bugs hidden in the js that are now visible, still a wip and currently only changes the webapp

**Review by balzack — APPROVED** [review]
The changes look good to me, and the local tests all work. Thanks!

**Comment by balzack** [comment]
I really appreciate your improvements and guidance. Thank you.

**Comment by balzack** [comment]
The github action is failing, but I think it can be resolved by changing actions/setup-node@v3 to v4.

Since all the tests work locally, I'll merge and update the main repo.

**Pull request merged**
